import type { LessonDefinition } from './types';

/** 为 public 目录资源补上 Vite 部署基路径，兼容本地开发与 GitHub Pages 子路径。 */
const publicAsset = (path: string) => `${import.meta.env.BASE_URL}${path}`;

export const LESSONS: LessonDefinition[] = [
  {
    kind: 'photo',
    id: 'color-dimensions', chapter: '第一章', shortTitle: '色彩三属性', title: '看见颜色的三个维度',
    sample: publicAsset('samples/lesson-1.webp'), sampleAlt: '中性日光中的多色桌面静物', sampleLabel: '中性光 · 多色静物',
    conceptTitle: '饱和度不是“颜色多少”',
    concept: '色相回答“是什么颜色”，饱和度描述颜色偏离灰色的程度，明度则决定它有多亮。一次只改变一个维度，更容易建立视觉记忆。',
    observe: '先找出画面中最醒目的颜色，再观察灰布是否仍然保持中性。',
    mistake: '只追求鲜艳会压缩细微层次，让不同材质看起来像同一种表面。',
    task: '把饱和度调到 +20 ～ +35，同时让明度保持在 -5 ～ +5。',
    success: '颜色更鲜明，明暗关系没有被破坏。', controls: 'global',
    constraints: [
      { kind: 'parameter', path: 'saturation', min: 20, max: 35, lowHint: '再提高一点饱和度，观察颜色与灰布的距离。', highHint: '饱和度过高，收回来一些以保留材质层次。' },
      { kind: 'parameter', path: 'lightness', min: -5, max: 5, lowHint: '画面整体变暗了，把明度拉回中性附近。', highHint: '画面整体变亮了，把明度拉回中性附近。' },
    ],
  },
  {
    kind: 'photo',
    id: 'white-balance', chapter: '第二章', shortTitle: '白平衡', title: '让中性色重新中性',
    sample: publicAsset('samples/lesson-2.webp'), sampleAlt: '暖钨丝灯下的咖啡桌与白色陶瓷杯', sampleLabel: '钨丝灯 · 暖色偏移',
    conceptTitle: '白平衡先找“应该中性”的物体',
    concept: '色温沿蓝—黄方向移动，色调沿绿—洋红方向移动。判断白平衡时，先寻找白杯、灰卡等本应接近中性的参照。',
    observe: '比较白杯高光和灰卡，它们是否被同一种暖黄色覆盖。',
    mistake: '为了“变冷”而过度降低色温，会把真实暖光氛围一起消除。',
    task: '降低色温至 -35 ～ -18，并让色调保持在 -8 ～ +8。',
    success: '中性物体恢复自然，现场的暖光氛围仍被保留。', controls: 'whiteBalance',
    constraints: [
      { kind: 'parameter', path: 'temperature', min: -35, max: -18, lowHint: '画面已经偏蓝，稍微恢复一些暖度。', highHint: '白杯仍然偏黄，继续降低一点色温。' },
      { kind: 'parameter', path: 'tint', min: -8, max: 8, lowHint: '绿色补偿过多，把色调拉回中间。', highHint: '洋红补偿过多，把色调拉回中间。' },
    ],
  },
  {
    kind: 'photo',
    id: 'color-harmony', chapter: '第三章', shortTitle: '色彩关系', title: '用色相距离理解画面张力',
    sample: publicAsset('samples/lesson-3.webp'), sampleAlt: '蓝绿色木门与橙色墙面的街景', sampleLabel: '街景 · 蓝橙互补',
    conceptTitle: '互补色来自色轮两端',
    concept: '色相相差约 180° 时形成互补关系，对比强、注意力集中；相邻色更和谐，适合营造统一氛围。',
    observe: '观察橙墙占据的大面积与蓝绿门的较小面积，面积并不相等但视觉仍然平衡。',
    mistake: '互补色不等于两种颜色都拉满饱和度；主次和面积比同样重要。',
    task: '转动两个色相点，让主色与强调色形成 170° ～ 190° 的色相距离。',
    success: '两个色相形成了清晰的互补关系。', controls: 'harmony',
    constraints: [{ kind: 'harmony', minDifference: 170, maxDifference: 190, hint: '继续拉开两个色相点，目标是位于色轮两端。' }],
  },
  {
    kind: 'photo',
    id: 'selective-hsl', chapter: '第四章', shortTitle: '分颜色 HSL', title: '只调整需要改变的颜色',
    sample: publicAsset('samples/lesson-4.webp'), sampleAlt: '暖色衣服的人像与绿色植物背景', sampleLabel: '人像 · 暖肤色与绿色背景',
    conceptTitle: '局部颜色调整需要软边界',
    concept: '真实照片中的颜色不会整齐地落在单一色相上。六色带采用柔和重叠，调整绿色时也会轻微影响相邻的黄色和青色。',
    observe: '先看背景叶片，再检查肤色与橙色衣服是否被连带改变。',
    mistake: '大幅移动色相容易制造不自然边缘；优先用饱和度和明度控制注意力。',
    task: '把绿色饱和度降到 -45 ～ -20，同时让橙色饱和度保持在 -10 ～ +10。',
    success: '背景绿色更克制，暖色主体仍然自然。', controls: 'bands',
    constraints: [
      { kind: 'parameter', path: 'bands.green.saturation', min: -45, max: -20, lowHint: '绿色已经过灰，适当恢复一些饱和度。', highHint: '背景仍然抢眼，继续降低绿色饱和度。' },
      { kind: 'parameter', path: 'bands.orange.saturation', min: -10, max: 10, lowHint: '橙色主体被削弱了，把橙色饱和度拉回中间。', highHint: '橙色主体过强，把橙色饱和度拉回中间。' },
    ],
  },
  {
    kind: 'photo',
    id: 'curves-grading', chapter: '第五章', shortTitle: '曲线与色调', title: '用明暗结构承载冷暖情绪',
    sample: publicAsset('samples/lesson-5.webp'), sampleAlt: '蓝调时刻中带暖色灯光的河岸城市', sampleLabel: '蓝调时刻 · 冷暖层次',
    conceptTitle: '先做层次，再添加颜色倾向',
    concept: 'S 曲线压低阴影、抬高高光以增加对比；随后再给阴影少量冷色、高光少量暖色，情绪才会依附于稳定的明暗结构。',
    observe: '留意暗部是否仍有细节，以及暖色灯光是否保持亮度层次。',
    mistake: '分离色调强度过大，会让灰色和肤色染成明显的双色滤镜。',
    task: '建立温和 S 曲线，并把冷阴影、暖高光强度都控制在 8 ～ 22。',
    success: '对比更清晰，冷暖色彩仍然克制。', controls: 'curve',
    constraints: [
      { kind: 'parameter', path: 'curve.1.y', min: 48, max: 60, lowHint: '阴影压得过重，抬高左侧控制点。', highHint: '再压低一点阴影，形成曲线下半段。' },
      { kind: 'parameter', path: 'curve.2.y', min: 204, max: 220, lowHint: '再抬高一点高光，形成曲线上半段。', highHint: '高光提升过多，降低右侧控制点。' },
      { kind: 'parameter', path: 'shadows.amount', min: 8, max: 22, lowHint: '增加少量冷阴影强度。', highHint: '冷阴影太明显，降低强度。' },
      { kind: 'parameter', path: 'highlights.amount', min: 8, max: 22, lowHint: '增加少量暖高光强度。', highHint: '暖高光太明显，降低强度。' },
    ],
  },
  {
    kind: 'mixer',
    id: 'additive-light',
    chapter: '第六章',
    shortTitle: '光色混合',
    title: '用 RGB 光线叠出新的颜色',
    conceptTitle: '光越叠加，结果越接近白',
    concept: '屏幕与摄影中的光采用加色混合。每束光先在线性空间累加能量，再编码回屏幕使用的 sRGB；红、绿、蓝等强叠加会得到白光。',
    observe: '预测前先判断每束光贡献了哪些 RGB 通道，再留意强度变化是否会触发通道裁剪。',
    mistake: '不要把光色与颜料混为一谈：红光加绿光是黄光，并不会得到棕色颜料。',
    task: '完成三个预测练习，再到自由调色盘改变每束光的独立强度。',
    model: 'additive-light',
    modelLabel: 'RGB 加色模型',
    presets: [
      { label: '红光', color: '#FF0000' },
      { label: '绿光', color: '#00FF00' },
      { label: '蓝光', color: '#0000FF' },
      { label: '暖橙', color: '#FF7A00' },
      { label: '紫光', color: '#B000FF' },
      { label: '青光', color: '#00DDEB' },
    ],
    exercises: [
      {
        id: 'light-red-green',
        prompt: '红光与绿光以相同强度叠加，会出现哪种光？',
        inputs: [
          { id: 'red', label: '红光', color: '#FF0000', amount: 100, enabled: true },
          { id: 'green', label: '绿光', color: '#00FF00', amount: 100, enabled: true },
        ],
        choices: [
          { id: 'orange', label: '橙光', color: '#FF7900' },
          { id: 'yellow', label: '黄光', color: '#FFFF00' },
          { id: 'brown', label: '棕色', color: '#7A471F' },
        ],
        correctAnswer: 'yellow',
        resultLabel: '黄光',
        explanation: '红光贡献 R 通道，绿光贡献 G 通道；两者等强相加得到 R+G，也就是黄光。',
      },
      {
        id: 'light-green-blue',
        prompt: '绿光与蓝光以相同强度叠加，会出现哪种光？',
        inputs: [
          { id: 'green', label: '绿光', color: '#00FF00', amount: 100, enabled: true },
          { id: 'blue', label: '蓝光', color: '#0000FF', amount: 100, enabled: true },
        ],
        choices: [
          { id: 'cyan', label: '青光', color: '#00FFFF' },
          { id: 'violet', label: '紫光', color: '#7B39E8' },
          { id: 'dark-green', label: '深绿', color: '#17633C' },
        ],
        correctAnswer: 'cyan',
        resultLabel: '青光',
        explanation: '绿光和蓝光分别点亮 G、B 通道，等强叠加得到青光。',
      },
      {
        id: 'light-rgb-white',
        prompt: '红、绿、蓝三色光等强叠加，最终会接近什么颜色？',
        inputs: [
          { id: 'red', label: '红光', color: '#FF0000', amount: 100, enabled: true },
          { id: 'green', label: '绿光', color: '#00FF00', amount: 100, enabled: true },
          { id: 'blue', label: '蓝光', color: '#0000FF', amount: 100, enabled: true },
        ],
        choices: [
          { id: 'gray', label: '中灰', color: '#808080' },
          { id: 'white', label: '白光', color: '#FFFFFF' },
          { id: 'black', label: '黑色', color: '#000000' },
        ],
        correctAnswer: 'white',
        resultLabel: '白光',
        explanation: '三个 sRGB 主通道都达到最大值时形成白光；光的叠加使能量增加，而不是变暗。',
      },
    ],
  },
  {
    kind: 'mixer',
    id: 'pigment-tone',
    chapter: '第七章',
    shortTitle: '颜料与综合色调',
    title: '比较颜料减色与 tint、tone、shade',
    conceptTitle: '颜料混合会吸收更多光',
    concept: '颜料采用减色混合：每种材料吸收一部分波段，混合后通常更暗、更灰。加入白、灰、黑则分别形成 tint、tone、shade。',
    observe: '比较混合前后的明度与纯度，观察“综合色”如何随颜料份数和中性色变化。',
    mistake: '屏幕上的光谱模拟是教学近似，真实颜料还会受材质、浓度、纸张和光源影响。',
    task: '完成三个预测练习，并在自由调色盘中比较白、灰、黑对同一颜色的影响。',
    model: 'spectral-pigment',
    modelLabel: 'Kubelka–Munk 光谱近似',
    presets: [
      { label: '钴蓝', color: '#002185' },
      { label: '黄色', color: '#FCD200' },
      { label: '朱红', color: '#D9272E' },
      { label: '青色', color: '#00A6C8' },
      { label: '白色', color: '#FFFFFF' },
      { label: '中灰', color: '#808080' },
      { label: '黑色', color: '#000000' },
    ],
    exercises: [
      {
        id: 'pigment-blue-yellow',
        prompt: '钴蓝与黄色颜料等份混合，最可能得到哪种综合色？',
        inputs: [
          { id: 'cobalt', label: '钴蓝', color: '#002185', amount: 50, enabled: true },
          { id: 'yellow', label: '黄色', color: '#FCD200', amount: 50, enabled: true },
        ],
        choices: [
          { id: 'bright-white', label: '亮白', color: '#FFFFFF' },
          { id: 'green', label: '绿色系', color: '#3D933E' },
          { id: 'violet', label: '紫色系', color: '#7546A8' },
        ],
        correctAnswer: 'green',
        resultLabel: '绿色系颜料',
        explanation: '蓝、黄颜料共同吸收更多波段，剩余反射以绿色为主；光谱近似结果约为 #3D933E。',
      },
      {
        id: 'pigment-complements',
        prompt: '红色与青色这组互补颜料等份混合，纯度和明度通常怎样变化？',
        inputs: [
          { id: 'red', label: '朱红', color: '#D9272E', amount: 50, enabled: true },
          { id: 'cyan', label: '青色', color: '#00A6C8', amount: 50, enabled: true },
        ],
        choices: [
          { id: 'neutral', label: '更暗、更灰的中性色', color: '#565058' },
          { id: 'white', label: '高亮白色', color: '#FFFFFF' },
          { id: 'saturated', label: '更鲜艳的洋红', color: '#F000B8' },
        ],
        correctAnswer: 'neutral',
        resultLabel: '较暗的灰紫中性色',
        explanation: '互补颜料吸收的波段相互补充，综合色纯度下降且通常更暗，本组近似为 #565058。',
      },
      {
        id: 'pigment-tint-tone-shade',
        comparisons: [
          { label: 'Tint · 蓝色 + 白色', inputs: [
            { id: 'blue', label: '蓝色', color: '#2F55A4', amount: 50, enabled: true },
            { id: 'white', label: '白色', color: '#FFFFFF', amount: 50, enabled: true },
          ] },
          { label: 'Tone · 蓝色 + 灰色', inputs: [
            { id: 'blue', label: '蓝色', color: '#2F55A4', amount: 50, enabled: true },
            { id: 'gray', label: '灰色', color: '#808080', amount: 50, enabled: true },
          ] },
          { label: 'Shade · 蓝色 + 黑色', inputs: [
            { id: 'blue', label: '蓝色', color: '#2F55A4', amount: 50, enabled: true },
            { id: 'black', label: '黑色', color: '#000000', amount: 50, enabled: true },
          ] },
        ],
        prompt: '同一蓝色分别加入白、灰、黑时，哪组术语匹配正确？',
        inputs: [
          { id: 'blue', label: '蓝色', color: '#2F55A4', amount: 50, enabled: true },
          { id: 'white', label: '白色', color: '#FFFFFF', amount: 50, enabled: true },
        ],
        choices: [
          { id: 'tts', label: '白 → Tint · 灰 → Tone · 黑 → Shade', color: '#83B0E0', swatches: ['#83B0E0', '#4E6E8A', '#2B3F4F'] },
          { id: 'stt', label: '白 → Shade · 灰 → Tint · 黑 → Tone', color: '#2B3F4F', swatches: ['#2B3F4F', '#83B0E0', '#4E6E8A'] },
          { id: 'tst', label: '白 → Tone · 灰 → Shade · 黑 → Tint', color: '#4E6E8A', swatches: ['#4E6E8A', '#2B3F4F', '#83B0E0'] },
        ],
        correctAnswer: 'tts',
        resultLabel: 'Tint、Tone、Shade',
        explanation: '加入白色提高明度形成 tint；加入灰色降低纯度形成 tone；加入黑色降低明度形成 shade。',
      },
    ],
  },
];
